markdown: kramdown
highlighter: pygments
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github: histoirexsr
author: "sofi"
email: hihihihihi@gmail.com
name: "chisin momo's site"
url: 
domain: 
baseurl: "https://histoirexsr.github.io/siteeeee"
all_categories: [
["life", "Life","https://histoirexsr.github.io/siteeeee/posts/life.html"], 
["tech", "Wine Tech","https://histoirexsr.github.io/siteeeee/posts/tech.html"],
["note", "Tasting Notes","https://histoirexsr.github.io/siteeeee/posts/note.html"], 
["event", "Events!","https://histoirexsr.github.io/siteeeee/posts/event.html"],
["review", "Wine Review","https://histoirexsr.github.io/siteeeee/posts/review.html"], 
["other", "Others","https://histoirexsr.github.io/siteeeee/posts/other.html"],
["about", "About","https://histoirexsr.github.io/siteeeee/about.html"],
["gallery", "Gallery","https://histoirexsr.github.io/siteeeee/gallery/index.html"]
]

# ["no idea", "name in toolbar", "link to html"]
paginate: 4
paginate_path: "posts/page:num"
timezone: America/Los_Angeles

collections:
  docs:
    output: true

gems:
 - jekyll-paginate

theme: jekyll-theme-minimal