markdown: kramdown
highlighter: pygments
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github: histoirexsr
author: "sofi"
email: hihihihihi@gmail.com
name: "chisin momo's site"
url: 
domain: 
baseurl: "/Users/sofifung/Documents/jekyll/jekyllnew_personal/_site"
all_categories: [
["life", "Life","/Users/sofifung/Documents/jekyll/jekyllnew_personal/_site/posts/life.html"], 
["tech", "Wine Tech","/Users/sofifung/Documents/jekyll/jekyllnew_personal/_site/posts/tech.html"],
["note", "Tasting Notes","/Users/sofifung/Documents/jekyll/jekyllnew_personal/_site/posts/note.html"], 
["event", "Events!","/Users/sofifung/Documents/jekyll/jekyllnew_personal/_site/posts/event.html"],
["review", "Wine Review","/Users/sofifung/Documents/jekyll/jekyllnew_personal/_site/posts/review.html"], 
["other", "Others","/Users/sofifung/Documents/jekyll/jekyllnew_personal/_site/posts/other.html"],
["about", "About","/Users/sofifung/Documents/jekyll/jekyllnew_personal/_site/about.html"],
["gallery", "Gallery","/Users/sofifung/Documents/jekyll/jekyllnew_personal/_site/gallery/index.html"]
]

# ["no idea", "name in toolbar", "link to html"]
paginate: 4
paginate_path: "posts/page:num"
timezone: America/Los_Angeles

collections:
  docs:
    output: true

gems:
 - jekyll-paginate
